### ISSUE TITLE
Build Action: Soft Copy Task

### ISSUE THREAD

**Issue by gruenwaldlk** [AlamoEngine-Tools/eaw-ci#16]
**As an** EaW Mod Developer  
**I want** to be able to specify a soft copy task in the build configuration that links files or whole sub directory trees from a path relative to the build configuration file to a target directory relative to the build configuration file  
**in order to** create a simple "working directory" that is structured in the same way as a functional mod and keep changes made there in sync with the repository.

* [x] **AC1:** The Soft Copy Task is identical in function to the Copy Task.
* [x] **AC2:** The Soft Copy Task does not actually copy files on the files system but instead creates Hard Links so the "working directory" and the repository stay synchronized.

**Comment by SvenMarcus** [comment]
.NET Core seems to be lacking an API for creating links. Do we want to start a native process for that?

**Comment by gruenwaldlk** [comment]
We probably have to unless there's a library that we can use.
From what I can gather from the various (heated) discussions on the .NET Core project - native support is way off, and all implementations that I found at some point turn to `Kernel32.dll` at some point to use the provided API:

```csharp
[DllImport("Kernel32.dll", CharSet = CharSet.Unicode )]
static extern bool CreateHardLink(
      string lpFileName,
      string lpExistingFileName,
      IntPtr lpSecurityAttributes
);
```

Alternatively we could use:
```csharp
Process.Start("mklink /H", string.Format("{0} {1}", link, target));
```
That's just notoriously slow for larger trees.

**Comment by SvenMarcus** [comment]
Mhm that's what I found as well. Question is what do we do on non Windows machines? I guess our only option there is going with `Process.Start("ln", "link target")`?
When using soft links we can link an entire directory, although that does mean we lose file pattern matching.

**Comment by gruenwaldlk** [comment]
> Also given that mod stacking is a thing now and this would primarily be used during development to avoid copying large amounts of data, we could probably think about delaying this until we we have a good solution for this.

That is a good point - to keep the tool "OS-agnostic" we'd have to use some sort of logic like that:
```csharp
if(IsWindows()){
    Process.Start("mklink /H", string.Format("{0} {1}", link, target));
}
else {
    Process.Start("ln", "link target")
}
```
Of course that can be handled in a prettier way - but in the end it'd boil down to that.
So, yes - with stacking being viable we don't really need the feature ASAP.

**Comment by SvenMarcus** [comment]
I found this on SO:
```C#
[DllImport ("libc.so")]
public static int link(string oldpath, string newpath)
```

If this works for Linux (and I assume for macOS it'll be similar, except that the library providing ln is libSystem.B.dylib) we could perhaps avoid starting another process for every file.

**Comment by SvenMarcus** [comment]
Soft Copy seems to work on all systems now, so I'm closing this
